version: '3.5'

services:
    postgres:
        image: postgres:11.4-alpine
        ports:
            - "5432:5432"
        volumes:
            - postgres:/var/lib/postgresql

volumes:
    postgres: ~
